#!/bin/bash

echo "* Running uicache..."
echo "* 执行刷新图标缓存中..."

su mobile -c uicache

echo "* Running uicache... Done."
echo "* 执行刷新图标缓存中... 完成"

echo "* Thanks for using My Repo Tweaks.Acreson wishes every jailbreak player a good time！"
echo "* 感谢使用本源插件.嘻哈祝每个越狱玩家玩得开心！"


exit 0;